server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        return 301 /restaurant-1/;
    }

    location /restaurant-1/ {
        try_files $uri $uri/ /restaurant-1/index.html;
    }
}
