server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        return 301 /fireline-burgers/;
    }

    location /fireline-burgers/ {
        try_files $uri $uri/ /fireline-burgers/index.html;
    }
}
