server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        return 301 /kairo-sushi/;
    }

    location /kairo-sushi/ {
        try_files $uri $uri/ /kairo-sushi/index.html;
    }
}
