server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        return 301 /olive-grain/;
    }

    location /olive-grain/ {
        try_files $uri $uri/ /olive-grain/index.html;
    }
}
