server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        return 301 /harvest-room/;
    }

    location /harvest-room/ {
        try_files $uri $uri/ /harvest-room/index.html;
    }
}
